export const problems = [
  {
    questionId: 1,
    name: "Batched Counter Updates",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 2,
    name: "Direct Object State Mutation",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 3,
    name: "Repeated Toggle Updates",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 4,
    name: "Missing Effect Dependency",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 5,
    name: "Timer State and Cleanup",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 6,
    name: "Broken Search Debounce",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 7,
    name: "Conditional Hook Call",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 8,
    name: "Todo Array Mutation",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 9,
    name: "Missing Event Parameter",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 10,
    name: "Fetching During Render",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 11,
    name: "Lost Profile State",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 12,
    name: "Resize Listener Cleanup",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 13,
    name: "Stale Closure in Interval",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 14,
    name: "Uncontrolled to Controlled Input",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 15,
    name: "Incorrect Cart Item Removal",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 16,
    name: "Unstable List Keys",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 17,
    name: "Sorting State In Place",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 18,
    name: "Async Effect Callback",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 19,
    name: "Overwritten Form Fields",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 20,
    name: "Infinite Fetch Effect",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 21,
    name: "Missing Context Provider Value",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 22,
    name: "Unstable Props with React.memo",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 23,
    name: "Accumulating Scroll Listeners",
    difficulty: "medium",
    maxTime: 20,
  },
  {
    questionId: 24,
    name: "State Update During Render",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 25,
    name: "Missing JSON Method Call",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 26,
    name: "Unsafe Comment HTML",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 27,
    name: "Visible Password Input",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 28,
    name: "Incorrect Online Event Handlers",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 29,
    name: "Missing Web Worker Cleanup",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 30,
    name: "Unsafe Stored Settings Initialization",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 31,
    name: "Unexpected Form Page Reload",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 32,
    name: "Protected Page Authentication State",
    difficulty: "medium",
    maxTime: 20,
  },
  {
    questionId: 33,
    name: "Incorrect Navigate Usage",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 34,
    name: "Redux Fetch Effect Setup",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 35,
    name: "Unstable Redux Selector Result",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 36,
    name: "Stale Memoized Search Results",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 37,
    name: "Stale Todo Callback",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 38,
    name: "Layout Measurement Effect",
    difficulty: "medium",
    maxTime: 20,
  },
  {
    questionId: 39,
    name: "Reducer State Mutation",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 40,
    name: "Missing Error Boundary Fallback",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 41,
    name: "Async Client Component with Suspense",
    difficulty: "hard",
    maxTime: 30,
  },
  {
    questionId: 42,
    name: "Clock Hydration Mismatch",
    difficulty: "hard",
    maxTime: 25,
  },
  {
    questionId: 43,
    name: "Missing Route Redirect Return",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 44,
    name: "Missing GraphQL Query Variables",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 45,
    name: "Apollo Cache Cleared on Mount",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 46,
    name: "Incomplete React Query Cache Key",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 47,
    name: "Invalid SWR Fetcher",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 48,
    name: "Lost WebSocket Messages",
    difficulty: "medium",
    maxTime: 20,
  },
  {
    questionId: 49,
    name: "Video Stream Assignment and Cleanup",
    difficulty: "hard",
    maxTime: 25,
  },
  {
    questionId: 50,
    name: "Canvas Ref Effect Dependencies",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 51,
    name: "Animation Frame Cleanup",
    difficulty: "medium",
    maxTime: 15,
  },
  {
    questionId: 52,
    name: "Inaccessible SVG Icon Button",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 53,
    name: "Invalid Grid Column Style",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 54,
    name: "Incorrect Flex Alignment Property",
    difficulty: "easy",
    maxTime: 5,
  },
  {
    questionId: 55,
    name: "Repeated Shadow Root Attachment",
    difficulty: "medium",
    maxTime: 20,
  },
  {
    questionId: 56,
    name: "Stale Sanitized HTML",
    difficulty: "easy",
    maxTime: 10,
  },
  {
    questionId: 57,
    name: "Frozen Configuration Mutation",
    difficulty: "easy",
    maxTime: 10,
  },
];
